### ISSUE TITLE
Feature Request: Add update mode without restarting the casper-node

### ISSUE THREAD

**Issue by GuybrushX** [casper-network/casper-node-launcher#32]
Currently if an update for casper-node-launcher is available via apt update the upgrade will completely stop and start the casper-node process, too.

I think this is unnecessary and should be avoided to keep the uptime of the node uninterrupted.

If I remember correctly when I upgraded the casper-node-launcher about 2 or 3 months ago I think it even killed the casper-node process in an ungraceful way causing a trie-state check but not sure about this and I don't want to test it for obvious reasons ;-)

Is an upgrade mode possible?

**Comment by sacherjj** [comment]
This isn't possible in a stable way because the casper-node-launcher will start the casper-node as a child process.  It would require detaching process and hoping to join back onto it.  We have drastically decreased the restart time of the casper-node with 1.4.3+.  You would update casper-node-launcher at times that you already need to perform security updates to the base Linux system.
